### ISSUE TITLE
Redis module for command bumper has wrong default prefix

### ISSUE THREAD

**Issue by hilkeheremans** [adrai/node-cqrs-domain#64]
Tiny bug. While traversing your code I visually spotted that the default prefix in the command bumper for redis is still set to "aggregatelock". You probably want something like "commandbumper" instead.

(Off-topic: Aside from that, GREAT work on all of your cqrs-related modules, @adrai! For broad acceptance and understanding you'll need plenty more documentation, but it's getting there. I would suggest making some visuals instead of just text, to more easily spot how everything interacts. I can try to help out at some point when I can.)

**Comment by adrai** [comment]
For sure! Thanks!
ANY type of contribution is helpful! :-)



Il giorno 24-dic-2015, alle ore 10:13, Hilke Heremans <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Tiny bug While traversing your code I visually spotted that the default prefix in the command bumper for redis is still set to "aggregatelock" You probably want something like "commandbumper" instead

(Off-topic: Aside from that, GREAT work on all of your cqrs-related modules, @adrai<https://github.com/adrai>! For broad acceptance and understanding you'll need plenty more documentation, but it's getting there I would suggest making some visuals instead of just text, to more easily spot how everything interacts I can try to help out at some point when I can)

-
